<template>
	<div :style="styleObject" ref="sceneContainer">
		<PolygonjsScene
			:loadFunction="loadFunction"
			:sceneName="'scene_01'"
			@sceneready="onSceneReady"
		/>
		<div :style="topBarStyleObject">
			<button @click="count++">increment</button>
			<div ref="vueElement">my vue element 1 ({{ count }})</div>
		</div>
	</div>
</template>

<script lang="ts">
import { defineComponent, ref, watch, computed, StyleValue } from "vue";
import { PolygonjsScene } from "@polygonjs/vue3";
import { loadScene_scene_01 } from "./scene_01/autogenerated/loadScene";
import type { PolySceneWithNodeMap_scene_01 } from "./scene_01/autogenerated/PolySceneWithNodeMap";

export default defineComponent({
	name: "scene-01",
	components: {
		PolygonjsScene,
	},
	setup() {
		let scene: PolySceneWithNodeMap_scene_01 | undefined;
		const sceneContainer = ref<HTMLElement|null>(null)
		const count = ref(0)
		const vueElement = ref<HTMLElement|null>(null)

		function onSceneReady(loadedScene: PolySceneWithNodeMap_scene_01) {
			scene = loadedScene;
			moveDOMElementToCSSObjects()
		}
		const loadFunction = computed(() => loadScene_scene_01);

		const styleObject = computed<StyleValue>(()=>{
            return {
				position: 'relative',
                width:'100%',
                height:'100%',
            }
        })
		const topBarStyleObject = computed<StyleValue>(()=>{
            return {
                position: 'absolute',
                top: '0px',
                left: '0px',
                width: '100px',
                backgroundColor: 'black',
                color: 'white',
            }
        })

		function moveDOMElementToCSSObjects(){
			if(!sceneContainer.value){
                return
            }
			if(!vueElement.value){
                return
            }
			if(!scene){
                console.warn('no scene but really it should be here!')
                return
            }

			const CSSObjectElements = Array.from(sceneContainer.value.querySelectorAll('.CSS2DObject')) as HTMLElement[];
            const firstElement = CSSObjectElements[0]
            firstElement.appendChild(vueElement.value);
		}

		return {
			count,
			sceneContainer,
			vueElement,
			loadFunction,
			onSceneReady,
			styleObject,
			topBarStyleObject
		};
	},
});
</script>

<style></style>
