<template>
	<div :style="styleObject" ref="sceneContainer">
		<PolygonjsScene
			:loadFunction="loadFunction"
			:sceneName="'scene_02'"
			@sceneready="onSceneReady"
		/>
		<div :style="topBarStyleObject">
			<button @click="count++">increment</button>
            <div>{{ CSSObjectsCountRange.length }}</div>
			<div v-for="i of CSSObjectsCountRange" ref="vueElement">my vue element 1 ({{ count }})</div>
		</div>
	</div>
</template>

<script lang="ts">
import { defineComponent, ref, computed, StyleValue, watch,nextTick } from "vue";
import { PolygonjsScene } from "@polygonjs/vue3";
import { loadScene_scene_02 } from "./scene_02/autogenerated/loadScene";
import type { PolySceneWithNodeMap_scene_02 } from "./scene_02/autogenerated/PolySceneWithNodeMap";

export default defineComponent({
	name: "scene-01",
	components: {
		PolygonjsScene,
	},
	setup() {
		let scene: PolySceneWithNodeMap_scene_02 | undefined;
		const sceneContainer = ref<HTMLElement|null>(null)
        const CSSObjectsCount=ref(0)
		const count = ref(0)
		const vueElement = ref<HTMLElement[]|null>(null)

		function onSceneReady(loadedScene: PolySceneWithNodeMap_scene_02) {
			scene = loadedScene;
			setCSSObjectsCount()
		}
		const loadFunction = computed(() => loadScene_scene_02);

		const styleObject = computed<StyleValue>(()=>{
            return {
				position: 'relative',
                width:'100%',
                height:'100%',
            }
        })
		const topBarStyleObject = computed<StyleValue>(()=>{
            return {
                position: 'absolute',
                top: '0px',
                left: '0px',
                width: '100px',
                backgroundColor: 'black',
                color: 'white',
            }
        })

        function getCSSObjects():HTMLElement[]{
            if(!sceneContainer.value){
                return []
            }
            return Array.from(sceneContainer.value.querySelectorAll('.CSS2DObject')) as HTMLElement[];
        }

		function setCSSObjectsCount(){
            CSSObjectsCount.value = getCSSObjects().length;
		}

        const CSSObjectsCountRange = computed(()=>  [...Array(CSSObjectsCount.value).keys()])

        watch(CSSObjectsCount, moveDOMElementToCSSObjectsLater)

        function moveDOMElementToCSSObjectsLater(){
            // we move the objects on nextTick,
            // to ensure that they have been created
            nextTick(moveDOMElementToCSSObjects)
        }

        function moveDOMElementToCSSObjects(){
            const CSSObjects = getCSSObjects();
            const vueDOMElements = vueElement.value
            if(!vueDOMElements){
                return
            }
            const minCount = Math.min(CSSObjects.length, vueDOMElements.length)
            for(let i=0; i<minCount;i++){
                const CSSObject = CSSObjects[i]
                const vueDOMElement = vueDOMElements[i];
                CSSObject.appendChild(vueDOMElement);
            }
        }

		return {
            CSSObjectsCountRange,
			count,
			sceneContainer,
			vueElement,
			loadFunction,
			onSceneReady,
			styleObject,
			topBarStyleObject
		};
	},
});
</script>

<style></style>
